name: Create Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resources
        uses: actions/checkout@v2
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(date +%Y%m%d%H%M)
          release_name: $(date +%Y%m%d%H%M)
          draft: false
          prerelease: false